#!/usr/bin/python

import RPi.GPIO as GPIO
import sys

GPIO.setmode(GPIO.BCM)

device = sys.argv[1]
status = sys.argv[2]

if device == 'light':
  print "Communicating with Light"
  GPIO.setup(23, GPIO.OUT)
  port = 23
elif device == 'fan':
  print "Communicating with Fan"
  GPIO.setup(24, GPIO.OUT)
  port = 24

if status == 'on':
  print "Turning on Device"
  GPIO.output(port, 1)
else:
  print "Turning off Device"
  GPIO.output(port, 0)
